export const TOGGLE_MENU = 'TOGGLE_MENU';
export const SET_BREADCRUMBS = 'SET_BREADCRUMBS';
export const SHOW_PARTICIPANTS_DETAIL = 'SHOW_PARTICIPANTS_DETAIL';
export const HIDE_PARTICIPANTS_DETAIL = 'HIDE_PARTICIPANTS_DETAIL';
export const TOGGLE_SCOREBOARD = 'TOGGLE_SCOREBOARD';
